services:
  kokoai-api:
    build: .
    container_name: kokoai-api
    env_file:
      - .env
    ports:
      - "8077:8077"
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: kokoai-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - kokoai-api

  db:
    image: postgres:17
    container_name: kokoai-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kokoai_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql
